#!/usr/bin/env bash
# Displays the time for 12 horus and 59 minutes.
#   Displays hours from 0 to 12
#   Displays minutes from 1 to 59

hr=0

while [ $hr -le 12 ]
do
  echo "Hour: $hr"
  mins=1
  while [ $mins -le 59 ]
  do
    echo "$mins"
    (( mins++ ))
  done
  (( hr++ ))
done
